# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  flutterVersion: '3.22.1'
  appVersion: '1.0.0+1'  # Define your custom version here
  androidHome: /usr/local/lib/android/sdk

steps:
- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

- script: |
    sudo apt-get update
    sudo apt-get install -y lib32stdc++6 lib32z1 unzip
  displayName: 'Install dependencies'

- script: |
    sudo mkdir -p $androidHome/cmdline-tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O commandlinetools.zip
    sudo unzip commandlinetools.zip -d $androidHome/cmdline-tools
    sudo mkdir -p $androidHome/cmdline-tools/latest
    sudo mv $androidHome/cmdline-tools/cmdline-tools/* $androidHome/cmdline-tools/latest/
  displayName: 'Download and install Android command-line tools'

- script: |
    yes | $androidHome/cmdline-tools/latest/bin/sdkmanager --sdk_root=$androidHome "platform-tools" "platforms;android-30" "build-tools;30.0.3"
  displayName: 'Install Android SDK components'

- script: yes | $androidHome/cmdline-tools/latest/bin/sdkmanager --licenses
  displayName: 'Accept Android SDK licenses'

- script: |
    sed -i "s/^version:.*/version: $(appVersion)/" pubspec.yaml
  displayName: 'Set custom app version'

- task: FlutterBuild@0
  inputs:
    target: 'pub get'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
  displayName: 'Flutter Build apk'

- script: |
    echo "Build completed with version $(appVersion)"
  displayName: 'Output build version'

