# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: DownloadSecureFile@1
    displayName: 'Download Keystore File'
    inputs:
      secureFile: 'flutter-devops.jks'

  - script: |
      echo "storePassword=$(storePassword)" > key.properties
      echo "keyPassword=$(keyPassword)" >> key.properties
      echo "keyAlias=$(keyAlias)" >> key.properties
      echo "storeFile=$(System.DefaultWorkingDirectory)/flutter-devops.jks" >> key.properties
    displayName: 'Create key.properties File'

  - script: |
      docker build -t flutter-app .
    displayName: 'Build Docker Image'
  
  - script: |
      docker run --name flutter-build-container -v $(pwd):/app -w /app flutter-app flutter build appbundle
    displayName: 'Build App Bundle'

  - script: |
      docker run --rm flutter-app openssl version
      docker run --rm flutter-app flutter --version
    displayName: 'Check OpenSSL and Flutter Version'

  # Step 3: Copy Bundle from Docker Container to Host Machine
  - script: |
      docker cp flutter-build-container:/app/build/app/outputs/bundle/release/app-release.aab $(System.DefaultWorkingDirectory)/app-release.aab
      docker rm flutter-build-container
    displayName: 'Copy Bundle from Docker Container'

  # Step 4: Verify Bundle is in the correct path
  - script: |
      ls -la $(System.DefaultWorkingDirectory)/app-release.aab
    displayName: 'Verify Bundle Path'

  # Step 5: Publish Bundle as Artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/app-release.aab'
      artifactName: 'drop'
    displayName: 'Publish Bundle Artifact'

  - task: DownloadSecureFile@1
    displayName: 'Download Playstore API secure file'
    inputs:
      secureFile: 'devops.json'
  
  - script: |
      ls $(Agent.TempDirectory)
      ls $(System.DefaultWorkingDirectory)
      cp $(Agent.TempDirectory)/devops.json $(System.DefaultWorkingDirectory)/_SBK-DS.frontEnd
      ls $(System.DefaultWorkingDirectory)/_SBK-DS.frontEnd
    displayName: 'Move devops.json to _SBK-DS.frontEnd folder'
