# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: ghcr.io/cirruslabs/flutter:3.22.0-0.3.pre

variables:
  FLUTTER_PROJECT_PATH: '/app'

jobs:
- job: RunTests
  displayName: 'Run Flutter Tests'
  steps:
  - script: |
      cd $(FLUTTER_PROJECT_PATH)
      flutter pub get
    displayName: 'Get Flutter Dependencies'

  - script: |
      yes | flutter doctor --android-licenses
    displayName: 'Accept Android SDK Licenses'

  - script: |
      flutter test
    displayName: 'Run Flutter Tests'

  - script: |
      if [ $? -eq 0 ]; then
        echo "CI successful"
      else
        echo "CI failed"
        exit 1
      fi
    displayName: 'Check Test Status'
