# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  
  - script: flutter clean
    displayName: 'Clean Flutter Project'
    
  - script: |
      docker build -t flutter-app .
    displayName: 'Build Docker Image'
  - script: |
      docker run --rm -v $(System.DefaultWorkingDirectory):/app flutter-app flutter build apk
    displayName: 'Build Flutter App Bundle'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build/app/outputs/flutter-apk'
      ArtifactName: 'flutter-app-bundle'
      publishLocation: 'Container'
