# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: |
      docker build -t flutter-app .
    displayName: 'Build Docker Image'
  
  - script: |
      docker run --rm -v $(pwd):/app -w /app flutter-app flutter build apk
    displayName: 'Build APK'

  - script: |
      containerId=$(docker create flutter-app)
      docker cp $containerId:/app/build/app/outputs/flutter-apk/app-release.apk ./app-release.apk
      docker rm $containerId
    displayName: 'Copy APK from Docker Container'
