# azure-pipelines.yml
trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      docker build -t flutter-app .
    displayName: 'Build Docker Image'
